name: Deploy

on:
  push:
    branches: [main]
      pull_request:
      branch:
      - main

jobs:
  ci:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2


    - name: Test
  run: |  
    npm install
    npm run test

  -name: Deploy
  if: github.ref == 'refs/heads/main'
  env: 
    DEPLOY_URL: ${{ secrets.RENDER_DEPLOY }}

  run: |
    curl DEPLOY_URL